#!/bin/bash
set -e

# -L: folder exists and is a symbolic link.
if ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

lastpass_login() {
  echo "What is your LastPass login email?"
  read lastpass_email
  echo "Logging into LastPass..."
  lpass login $lastpass_email
}

lastpass_get() {
  # -f: file exists and is a regular file.
  if [ -f "$HOME/$3" ]
  then
    echo "$HOME/$3 already exists."
    return
  fi

  echo "Extracing $HOME/$3..."  
  lpass show "$1" --field="$2" > "$HOME/$3"
  chmod 600 "$HOME/$3"
}

lastpass_login

# Extract public and private keys from LastPass.
lastpass_get "security/SSH key id_rsa" "Public Key" ".ssh/id_rsa.pub"
lastpass_get "security/SSH key id_rsa" "Private Key" ".ssh/id_rsa"

echo "Storing SSH keys in keychain..."
ssh-add -K

# Logout without confirmation.
lpass logout -f
