#!/bin/bash
set -e

sudo_askpass() {
  if [ -n "$SUDO_ASKPASS" ]
  then
    # $@ refers to all command-line arguments.
    sudo --askpass "$@"
  else
    sudo "$@"
  fi
}

# Close System Preferences to prevent UI from overriding changes altered with this script.
osascript -e 'tell application "System Preferences" to quit'

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Set 'System Preferences → General → Automatically hide and show the menu bar' to 'on'.
defaults write -g _HIHideMenuBar -bool true

# Set 'System Preferences → Dock → Automatically hide and show the Dock' to 'on'.
defaults write com.apple.dock autohide -bool true

###############################################################################
# Localization                                                                #
###############################################################################

# Set 'Language & Region → General → First day of the week' to 'Monday'."
defaults write -g AppleFirstWeekday -dict gregorian 2
# BROKEN: this configuration has no effect on macOS Catalina!

# Set 'Language & Region → General → Time format' to '24h'.
defaults write -g AppleICUForce24HourTime -int 1

# Set 'Language & Region → General → Temperature' to 'Celsius'.
defaults write -g AppleTemperatureUnit -string "Celsius"

###############################################################################
# Security & Privacy                                                          #
###############################################################################

# Set 'Security & Privacy → General → Require password X after sleep or screen saver begins' to 'immediately'.
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0
# BROKEN: this configuration has no effect on macOS Catalina!

# Set 'Security & Privacy → Firewall' to 'on'.
sudo_askpass /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on

# Turn on firewall logging.
sudo_askpass /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on

# Set 'Security & Privacy → Firewall → Options → Block all incoming connections' to 'on'.
sudo_askpass /usr/libexec/ApplicationFirewall/socketfilterfw --setblockall on

# If you do not want to block all incoming connections you can make the following configurations instead.

# Set 'Security & Privacy → Firewall → Options → Automatically allow built-in software to receive incoming connections' to 'off'.
# sudo_askpass /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsigned off

# Set 'Security & Privacy → Firewall → Options → Automatically allow downloaded signed software to receive incoming connections' to 'off'.
# sudo_askpass /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsignedapp off

# Set 'Security & Privacy → Firewall → Enable stealth mode' to 'on'.
# sudo_askpass /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on

###############################################################################
# Network                                                                     #
###############################################################################

# Set 'Network → Wi-Fi → Advanced... → DNS' to Cloudflare DNS servers.
networksetup -setdnsservers Wi-Fi 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001

###############################################################################
# Finder                                                                      #
###############################################################################

# Set 'Advanced → Show all filename extensions' to 'on'.
defaults write -g AppleShowAllExtensions -bool true

###############################################################################
# Reminders                                                                   #
###############################################################################

# Set 'Preferences → All-Day Reminders → Today Notification' to '6am'.
defaults write com.apple.remindd todayNotificationFireTime -int 600

# Set 'Preferences → All-Day Reminders → Show all-day reminders as overdue' to 'on'.
defaults write com.apple.remindd showRemindersAsOverdue --bool true

###############################################################################
# Misc                                                                        #
###############################################################################

# Save to disk (not to iCloud) by default.
defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false

# Automatically quit printer app once the print jobs are complete.
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

echo "Done. Note that some of these changes require a logout/restart to take effect."