#!/bin/sh

sudo_askpass() {
  if [ -n "$SUDO_ASKPASS" ]; then
    sudo --askpass "$@"
  else
    sudo "$@"
  fi
}

# Install dotfiles into the home dir.

# Figure out current directory (script).
# Go one level up and use that directory.
DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

# Figure out whether we run on macOS or Linux.
[ $(uname -s) = "Darwin" ] && export MACOS=1
[ $(uname -s) = "Linux" ] && export LINUX=1

# Create symbolic links for these selected dotfiles only.
dotfiles=(.gitconfig .zshrc .Brewfile)

for DOTFILE in ${dotfiles[@]}
do
  # Target path that will be symlinked.
  HOMEFILE="$HOME/$DOTFILE"
  # If dotfile is a dir add trailing slash.
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  # Source path within dotfiles repo.
  DIRFILE="$DOTFILESDIR/$DOTFILE"

  # Check if target exists, is a symbolic link and is not a directory.
  if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
  then
    # Replace symbolic link.
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    # Replace file or folder with symbolic link.
    rm -rv "$HOMEFILE"
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi
done